### ISSUE TITLE
Ask for sudo password on Wayland

### ISSUE THREAD

**Issue by ghost** [papylhomme/diskmonitor#26] opened 2020-07-21 13:05 UTC
I've compiled and installed diskmonitor-git from the AUR in Arch Linux. On Plasma Wayland, DisKMonitor 0.3.4 will start, but no smart information will be shown and you get only the message "Unable to detect SMART support for this drive". When using "sudo smartctl -a /dev/nvme0" on the terminal, I can see all the smart details for this drive. I assume that when starting DisKMonitor it should ask for the sudo password.

**Comment by papylhomme** [comment] 2020-08-07 09:52
Sorry but it's a duplicate of #22, it won't be solved that easily.

Shortly, DisKMonitor is mainly a frontend for the udisks project, which in turn rely on libatasmart (NOT smartmontools), and the former still lack NVME support.

I'm checking on [this](https://github.com/storaged-project/udisks/issues/386) from time to time but it doesn't seem it will be supported real soon.

**Closed as completed by papylhomme** 2020-08-07 09:52 UTC
